tzindex:
  volume:
    storage: 10Gi
  image:
    registry: docker.io
    repository: mavrykdynamics/tzstats
    tag: v15.0.1
    pullPolicy: IfNotPresent
    pullSecret: docker-pull-credentials
  ingress:
    host: api-tzindex.mavryk.io
    secretName: api-tzindex-tls
  env:
    - name: TZ_RPC_URL
      value: http://tezos-baking-archive-node-rpc.basenet.svc.cluster.local
    - name: TZ_SERVER_HOST
      value: '0.0.0.0'
    - name: TZ_SERVER_ADDR
      value: '0.0.0.0'
    - name: TZ_SERVER_CORS_ENABLE
      value: 'true'
    - name: TZ_SERVER_CORS_ORIGIN
      value: '*'
    - name: TZ_LOG_LEVEL
      value: 'stdout'

tzstats:
  image:
    registry: docker.io
    repository: mavrykdynamics/tzstats
    tag: v0.0.2
    pullPolicy: IfNotPresent
    pullSecret: docker-pull-credentials
  ingress:
    host: explorer.mavryk.io
    secretName: explorer-tls
