spec:
  environment: network
  clusterName: network

basenet:
  valueFiles: network.values.yaml

certManager:
  valueFiles: network.values.yaml

externalDNS:
  valueFiles: network.values.yaml

kubePrometheusStack:
  valueFiles: network.values.yaml

promtail:
  valueFiles: network.values.yaml

sealedSecrets:
  valueFiles: network.values.yaml
