spec:
  environment: prod
  clusterName: in-cluster

argoCD:
  valueFiles: prod.values.yaml

certManager:
  valueFiles: prod.values.yaml

ingressNginx:
  valueFiles: prod.values.yaml

externalDNS:
  valueFiles: prod.values.yaml

kubePrometheusStack:
  valueFiles: prod.values.yaml

mavrykApi:
  valueFiles: prod.values.yaml

mavrykFinanceIndexer:
  valueFiles: prod.values.yaml

mavrykOracles:
  valueFiles: prod.values.yaml

metricsServer:
  valueFiles: prod.values.yaml

lokiDistributed:
  valueFiles: prod.values.yaml

promtail:
  valueFiles: prod.values.yaml

sealedSecrets:
  valueFiles: prod.values.yaml

thanos:
  valueFiles: prod.values.yaml
