spec:
  environment: prod
  valueFiles: prod.values.yaml
  clusterName: in-cluster

argoCD:
  valueFiles: prod.values.yaml

certManager:
  valueFiles: prod.values.yaml

externalDNS:
  valueFiles: prod.values.yaml

kubePrometheusStack:
  valueFiles: prod.values.yaml

sealedSecrets:
  valueFiles: prod.values.yaml

thanos:
  valueFiles: prod.values.yaml
