spec:
  environment: prod
  valueFiles: prod.values.yaml
  clusterName: in-cluster

argoCD:
  enabled: true

certManager:
  enabled: true

externalDNS:
  enabled: true

kubePrometheusStack:
  enabled: true

sealedSecrets:
  enabled: true
