bcdHub:
  envSecretName: bcd-hub-secret
  dockerPullSecret: docker-pull-credentials
  bcdEnv: sandbox
  sandboxNodeUri: https://basenet-baking-node.mavryk.network
  sandboxIpfsGateway: https://cloudflare-ipfs.com
  db:
    image:
      registry: docker.io
      pullPolicy: IfNotPresent
      repository: timescale/timescaledb
      tag: latest-pg15
  api:
    image:
      registry: docker.io
      pullPolicy: IfNotPresent
      pullSecret: docker-pull-credentials
      repository: mavrykdynamics/bcdhub-api
      tag: '4.7.2'
  indexer:
    image:
      registry: docker.io
      pullPolicy: IfNotPresent
      pullSecret: docker-pull-credentials
      repository: mavrykdynamics/bcdhub-indexer
      tag: '4.7.2'
  ingress:
    host: api-better-call.mavryk.io
    tls:
      enabled: true
      secretName: api-better-call-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'

bcd:
  image:
    registry: docker.io
    pullPolicy: IfNotPresent
    dockerPullSecret: docker-pull-credentials
    repository: mavrykdynamics/bcdhub-gui
    tag: '4.5.2'
  env:
    - name: NODE_ENV
      value: production
    - name: BASE_URL
      value: https://better-call.mavryk.io/
    - name: VUE_APP_API_URI
      value: https://api-better-call.mavryk.io/v1
    - name: VUE_APP_IPFS_NODE
      value: https://ipfs.io
  ingress:
    host: better-call.mavryk.io
    tls:
      enabled: true
      secretName: better-call-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/enable-cors: 'true'
      nginx.ingress.kubernetes.io/cors-expose-headers: '*'
      nginx.ingress.kubernetes.io/cors-allow-origin: '*'
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE, PATCH
