{{if .Values.ingressNginx }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.environment }}-ingress-nginx
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    name: {{ .Values.spec.clusterName }}
  project: default
  source:
    path: src/infrastructure/helm-charts/ingress-nginx
    repoURL: git@github.com:mavrykfinance/mavryk-dapp
    targetRevision: private-testnet
    helm:
      valueFiles:
        - {{ .Values.ingressNginx.valueFiles }}
{{end}}