{{if .Values.kubePrometheusStack.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.environment }}-kube-prometheus-stack
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-prometheus-stack
    name: {{ .Values.spec.clusterName }}
  project: default
  source:
    path: src/infrastructure/helm-charts/kube-prometheus-stack
    repoURL: git@github.com:mavrykfinance/mavryk-dapp
    targetRevision: private-testnet
    helm:
      valueFiles:
        - {{ .Values.spec.valueFiles }}
{{end}}