name: kube-prometheus-stack-mavryk
version: 0.0.1
apiVersion: v2
appVersion: v0.66.0
dependencies:
  - name: kube-prometheus-stack
    version: 48.3.1
    repository: https://prometheus-community.github.io/helm-charts
