oracles:
  bob:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1ezDb77a9jaFMHDWs8QXrKEDkpgGdgsjPD
      publicKey: edpktqePwpgrWGS49FiAMDacb3bLiDLE8BrbLoi6zYdcZ9bttDLo1D
      secretKey:
        secretName: oracle-keys
        key: TEZOS_SECRET_KEY_1
    p2p:
      peerId: 12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1
      peerPublicKey: CAESIH+cTTTZ4gyqjEsn4L17gs9BTYU1ZeAnrBbUqQQQ9uW2
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_1
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_1
  eve:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1bfkfgQ8EsH9wrFXueAvm8rKRxzab1vQH1
      publicKey: edpkv758sKsFGRwE3ZNDR1wdVEnxZui344fsxEtCKbpNMcTaQw2Yis
      secretKey:
        secretName: oracle-keys
        key: TEZOS_SECRET_KEY_2
    p2p:
      peerId: 12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2
      peerPublicKey: CAESIB3LuOsvQXa/QtLkCtHqfEdDnXDiDtGIKB42deJZQSZb
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_2
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_2
  mallory:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1TJTq4Rcx4hqCxkGnmwJRpqeDNzoEpjk6n
      publicKey: edpkv6mD1SBoUB45g6Ss3LYfYzqZGxRfA3dehYBxEvGidFzsCg6yXQ
      secretKey:
        secretName: oracle-keys
        key: TEZOS_SECRET_KEY_3
    p2p:
      peerId: 12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      peerPublicKey: CAESIJwuGA2Ua44At3SqYSvFPk/S4ZK8JIChdtEIHowkTCno
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_3
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_3
  alice:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1Rf4qAP6ZK19hR6Xwcwqz5778PnwNLPDBM
      publicKey: edpku8CdxqUzHhL8X3fgpCX5CfmqxUU7JWBTmXwqUATt78dGijvqWd
      secretKey:
        secretName: oracle-keys
        key: TEZOS_SECRET_KEY_4
    p2p:
      peerId: 12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34
      peerPublicKey: CAESIIpE2iakPl9DwCEBQe8byn/AbxyFyp/6wswDEjAzTPV/
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_4
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_4
  oscar:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1Zgg2vLeyYLwQCtChXKjYDAXCRowQTzEGw
      publicKey: edpkuTgScYTtrvAtTU6UMF44NvNd51ah1aqNeerNFC38bGZrKVXwFP
      secretKey:
        secretName: oracle-keys
        key: TEZOS_SECRET_KEY_5
    p2p:
      peerId: 12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5
      peerPublicKey: CAESIDlwJrvH3HgJbcpLpzROMCyxhAGuaodYse7n0tDQmtYq
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_5
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_5

image:
  pullSecret: docker-pull-credentials
  registry: docker.io
  repository: mavrykdynamics/mavryk-oracle
  tag: v0.1.12
  pullPolicy: Always

aggregatorsAddresses:
  - KT1JLUxqAB6aS1FKnRLWmcC64yDmNy72TkRz
  - KT1S26reU1fiXMXL6JDt3sR9h11coufFRRD1
  - KT1UmpNUn6CLU4cmL7GstvSpetXREaK4JQZV
  - KT1XjnbJx4UqQaaRWE8FobgTuucYhi3KL2Wf
