oracles:
  susie:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1TQ4fpSFNZ6D9vrcwBz9yzM2SNjDj5YoU7
      publicKey: edpkv6xHMqShSMr4CK3Vzg7mD1hina7eBkokrMoKpuYj55BVd18rjN
    p2p:
      peerId: 12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1
      peerPublicKey: CAESIH+cTTTZ4gyqjEsn4L17gs9BTYU1ZeAnrBbUqQQQ9uW2
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_1
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_1
  eve:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1T8S68igxa6uWZbeoWWwbcuRHEDQSzknEX
      publicKey: edpkuX5ihBUVb9nNqLYixvGiVJ5VXxnVk5hnf9ZMkTkvP5UsRsBWX6
    p2p:
      peerId: 12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2
      peerPublicKey: CAESIB3LuOsvQXa/QtLkCtHqfEdDnXDiDtGIKB42deJZQSZb
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_2
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_2
  trudy:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1dQNGEDPoapnJaK1nX5boVHYKcdtoMjKSq
      publicKey: edpkubMsp1wdfpARu3ZsHKwrtkR9PQiAN8nsACP2hiksb7oM5aUhpu
    p2p:
      peerId: 12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      peerPublicKey: CAESIJwuGA2Ua44At3SqYSvFPk/S4ZK8JIChdtEIHowkTCno
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_3
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_3
  alice:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1byTGaUKjJqkwSXPnM3dpf9N39pYwRfnTm
      publicKey: edpkuprQbBc5mg8nm1RN2M2mpDmu7b3XNeB9KzCSUFx7nZbqVJj3AM
    p2p:
      peerId: 12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34
      peerPublicKey: CAESIIpE2iakPl9DwCEBQe8byn/AbxyFyp/6wswDEjAzTPV/
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_4
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_4
  oscar:
    rpcUrl: https://uoi3x99n7c.ghostnet.tezosrpc.midl.dev
    tezos:
      address: tz1b3BQ8wFyQ9U5Gx8WWXimphY8ER8qorm7m
      publicKey: edpkutgoG8KknR6EFViM33SfALiptofnbBRTthPU28VXzs4mCwjxNU
    p2p:
      peerId: 12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5
      peerPublicKey: CAESIDlwJrvH3HgJbcpLpzROMCyxhAGuaodYse7n0tDQmtYq
      peerPrivateKey:
        secretName: oracle-keys
        key: P2P_PRIVATE_KEY_5
    alphavantage:
      secretName: oracle-keys
      key: ALPHAVANTAGE_API_KEY
    messari:
      secretName: oracle-keys
      key: MESSARI_API_KEY_5

image:
  pullSecret: docker-pull-credentials
  registry: docker.io
  repository: mavrykdynamics/mavryk-oracle
  tag: v0.2.5s
  pullPolicy: Always

aggregatorsAddresses:
  - KT1CvnSqj4KshdaY82x1zzeyA3Ev4TRz43PN
  - KT1LD3oMphstZmri9V3hekg2j1bmK5RZD75S
  - KT1LdeHnNGfmQNZAECwcS9FdNeQ9JgueVqhE
  - KT1VknikdyLaHvfZhfmMyF4ygfv7zbnpiHM6
