version: '3.6'
services:
  db:
    image: timescale/timescaledb:latest-pg15
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bcd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    logging: &bcd-logging
      options:
        max-size: 10m
        max-file: '5'

  api:
    restart: always
    platform: linux/amd64
    image: ghcr.io/mavryk-network/bcdhub-api:4.7.7
    environment:
      - BCD_ENV=sandbox
      - GIN_MODE=debug
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - db
    ports:
      - 127.0.0.1:14000:14000
    volumes:
      - bcdshare:/etc/bcd
    links:
      - 'flexmasa:sandbox'
    expose:
      - 14000/tcp
    logging: *bcd-logging

  indexer:
    restart: always
    platform: linux/amd64
    image: ghcr.io/mavryk-network/bcdhub-indexer:4.7.7
    environment:
      - BCD_ENV=sandbox
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SANDBOX_NODE_URI=http://sandbox:20000
      - SANDBOX_IPFS_GATEWAY=https://cloudflare-ipfs.com
    depends_on:
      - db
    links:
      - 'flexmasa:sandbox'
    volumes:
      - bcdshare:/etc/bcd
    logging: *bcd-logging

  flexmasa:
    container_name: mavryk-sandbox
    restart: always
    image: registry.gitlab.com/mavryk-network/flexmasa:boreas-update-run
    command: >
      flexmasa mini-net 
      --root "/tmp/mini-box" 
      --size 1
      --set-history-mode N000:archive 
      --number-of-boot 1
      --balance-of-bootstrap-accounts mav:100_000_000 
      --time-b 3 
      --add-bootstrap-account="alice,edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn,mv1Hox9jGJg3uSmsv9NTvuK7rMHh25cq44nv,unencrypted:edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq@2_000_000_000_000" 
      --add-bootstrap-account="bob,edpkurPsQ8eUApnLUJ9ZPDvu98E8VNj4KtJa1aZr16Cr5ow5VHKnz4,mv1NpEEq8FLgc2Yi4wNpEZ3pvc1kUZrp2JWU,unencrypted:edsk3RFfvaFaxbHx8BMtEW1rKQcPtDML3LXjNqMNLCzC3wLC1bWbAt@2_000_000_000_000" 
      --until-level 200_000_000 
      --protocol-kind "Atlas"
    environment:
      - flexmasa_node_cors_origin=*
    ports:
      - 127.0.0.1:20000:20000
      - 127.0.0.1:8732:20000
    expose:
      - 20000/tcp
      - 8732/tcp
    logging: *bcd-logging

  gui:
    container_name: sandbox-gui
    restart: always
    platform: linux/amd64
    image: ghcr.io/mavryk-network/bcdhub-gui:4.7.7
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80
    logging: *bcd-logging

volumes:
  bcdshare:
  db:
    driver: local
