apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-basic-auth
  namespace: thanos
spec:
  encryptedData:
    auth: AgASRLoLX8cPFe+6qwByvbjco0bvvPkkTJZBRL3KWrVsf79t0vMjnTHbsrxV161k/oxPKzoHx8kdKBuxbGvPLnWIw6O3Zc/kCnYwfJifWbF6jXercajE/AkHJEwg8aK8KRnuzatRRAcitlFpERGX8p2pmhhH93UwRmTb/P8m/blbSTX2KvJeNXbRI8/nhBXfgKA6IuHs21VxK8hBHQn33ZYclOpgwBGrfGG0YsXOuolP5EPNKa6kJ5zqj03iBMAyg8QwVw0G+kqvKrYgDDhig9/xL4vVs8CNXwcpBVuV80m0SWCzRVBBZk+L9cGHAWFCdvAuCENWFeFLwcn3kBAYV4oCgcAuIRHB8qY4qNVFuMWquQ49xGjTfUgNqi4nwcSfH8X3QcE9vNuoltOmpd9nN2J/yTsqcQoiBuKItsLQ9yJGGRJJ83I8lQEZSO/gN9qWuQHFOPt/yfCx1F53XwSvpLuFSRmuQcs+fdlvfEaPNrZ/vMrYHr6s8klSpPbBdYNUIJJVP1/6smkNW0o1VcCSQVPNnUN2juAOH0MnwORxEzCNvBVCHsg36tAVtLtVglnPsaqjsW3S21xejm5vkUPWDQJHRfDVFGfgjGiT8C/r8Dmo4rLi4ILD6mtkakiOAGVZMipiPGiLygBKHI83z91GDDqZYO2U4yVBdlJl/j+Vo0Jusc2l3IqTeXc0cklFg+ln//a6wOPeHqLwPb7JSqvJkdQULj56tcLyo/6nZQhF2vSET+3qksyDfXT/uZO0McY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ingress-basic-auth
      namespace: thanos
    type: Opaque

