apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-basic-auth
  namespace: thanos
spec:
  encryptedData:
    auth: AgAO+EMjM/Sti4MqHxJvPYHJ+bH1XJk7Gh7/1rpsuyDcM8LysQeVfJ6evh+6eNxHj7Hb9FY6rzKniuPHKiixF0dadVjvs+k/gnm81qYPhivILKU1Xsi1GfUl3LIGFYeoINavjxwVB/kHyC+RsBl2s2TjsszxPSiOoTkoOQcH7bs70wlAaOWUtKQqOn5qyL37IKTaLfzg3WlI0+g643OgnfTFucswrR78mYcrl9np8/6mztWjpKqGLXQfl+mxtLkecMUCEfKLJD3bYSfCSqI25sqEjmHBFjGne8sveVMd8Ltu+Ct3QWVZr0qeyH/swTl/mtbfokWHqaikuEHBIkyp7IvfGOKV9mbR1rQoSAW0aU2TBuJrKsON+rGsxfbzZJWkdWAdLcsjX7BuPSxib9Tw5P/N/y69ZRRGq3UfapqCwCeuy7rp59TzfvgTrHuThqOMGsacpUXnpuZ3qcF1ns6gWoCX47kuHZWAjn/+xfIp2RPPBaZ5GlV3wMRPuL8kQSmPgcwDX3g3l6tWRXSfL35ycw9G6Q1Aoj2MEORf9Zeyg/V6ORAOub6Gebur91SRRqsQPE4wvr9AqPcwjBfNHOhY1Lexfb+jP2mSJSEwjUGDXZTKxy9QP6weXmuZh7u+X7R2uG9vNkdVPADHdqRumH/55GBtYQhPpMgtTQ5sVk7hxBUcAOSO8dfJKl1KLXfJwKVMBb254nx4rIwhd/tpYU1L+dxh5wwg+jaX2WDa/0xHCS/OmafJFUIxxEnp9UkjlW4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ingress-basic-auth
      namespace: thanos
    type: Opaque

