apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress-basic-auth
  namespace: thanos
spec:
  encryptedData:
    auth: AgB7LkAgS8qItO1NJNgijN9ZOdvRbw7pAzw8zZBsNVZtpKKJK1EgniGOW5K4du13P80wjZxbRgYCakyK+tMeDczPjS/YFzsKwrGFik35NHlBGpleLKpsv1apzES785KaDOOJlv1bGmB4AP60GNHKEwQ9q+gEQG6xTuCwMVbcfKJ8n6y7eafbsj8ynM5GxvXrrG6hAPcZ+uaAqX3iWX/j7T1GY5FZDXN584gp0S3macXTjfIYmVtNVoB0LGoJ04sx8oQEiChMqfpyVuW6lI7qA7MBCdBnABOkPO8wChG/yFWjNCgwF/bqesx+p+IXBtG5QcxkP/mGgbaBrMYiGqwQ3TmAoGHdYzPn94Si5xdXA6y3W3rDxNm68liLaodXpfraGnXIWhWOlnmANGka4mJs8M3sKga0GesrbFeV3XFpBAykiE12dmeW+ZOfPmUzjMTvkMf4RYPZ7FKHs3fAtvxEwlVWsvYuy/LKYLlvwkYytaGRH6JIuADPIdVF4Jkwnu0ZpKNSQUP5RMUcGLHiiUoukNq1XWSlMYGCu989sSSPvn4J4eAH2/Fwq8mN9T4cCi7UcI8t7U1fltk5DxwLW7B9ozPqaPlUmX6R4ztYNiLahJAUdrYa9IJrf5p2hH+f3NZs3uigAIqFmTBN9QFt6GKADCEjXQM6oVm6PHC1PDo91iMYeLF81lmKCzdp/7s6qhgVoLu8Ul912f/V/IXPtoG7vQ9plWWesbgKbukm+RglDJgluWBX7ijVdnVuBPGx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ingress-basic-auth
      namespace: thanos
    type: Opaque

