version: "3.8"

services:
  # indexer:
  #   build: .
  #   depends_on:
  #     - db
  #     - hasura
  #   restart: "no"
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
  #     - ADMIN_SECRET=${ADMIN_SECRET:-changeme}
  #     - TZKT_URL=${TZKT_URL:-changeme}

  db:
    image: timescale/timescaledb:latest-pg13
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    environment: 
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=dipdup12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1

  hasura:
    image: hasura/graphql-engine:v2.23.0
    ports:
      - 127.0.0.1:42000:8080
    depends_on:
      - db
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://dipdup:dipdup12345@db:5432/dipdup
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
      - HASURA_GRAPHQL_ADMIN_SECRET=hasura12345
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=user
      - HASURA_GRAPHQL_ENABLE_ALLOWLIST=false
      - HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true
  
volumes:
  db: