[tool.poetry]
name = "mavryk-indexer"
version = "0.1.0"
description = ""
authors = ["Tristan ALLAIRE <tristan.allaire@alarch.fr>"]

[tool.poetry.dependencies]
python = "^3.10"
dipdup = "5.0.0rc1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
