[tool.poetry]
name = "mavryk-indexer"
version = "0.1.0"
description = ""
authors = ["Tristan Allaire <tristan@tezosdynamics.com>"]

[tool.poetry.dependencies]
python = "^3.10"
dipdup = "5.1.1"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
