apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-grafana
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgA7t733TjZeRxT2FFI8Lse6Xcn4WTHbiV1Bi9iv0nJWiX0WmjaAf8mDWZpJGrlCztrgSJkFFBkzyVaaYz8S1pKWHNhLAzfJeoMCqZd+3oi+mMYoawrEuzPNPWq+EvgEX9420UAwpk7Z3tssGe3FkYwpFpuWTIye+kpea8SYzfUdbBHXbP0730YGLn2NjXwKOEZC+J6tcZBryXpC6TtpdGDoPtOipDhyHrfb5KtW8pneUeX74OnrwjlNZnT3ZT2qUje/hdtY5fwPTxEj3p+J8hG9tSLtLgiT3pfHfyM6SQ4SuRWJZyrc/Nt5k1ILQkDnwkyeWDwLJ49MNlN7kj/UY9SSGW6qydO3ldHkM8lBg5izohaER1s4E56V0EanwP7HDTUHkDWC+84xqSr5rBqxzLwl4plA2i+8lExysxs4bnG/8T3LodH1bdTe7RZ0THC4PyfWvX6l/26UAEC+iAKeHjuI8pDX+1OxhTIdD/YwvMQ+ps7CDFsgfEAu8Ql+BT/U1bdcBFKM2kBds3SrYGHn2iiqITQZm1XGvr1cFAL0AddKUTH2nUKXRiXJd1rodz8z11gcQ8hfjvAU/8JhxFg/3r4LoMOcoU8+5CgldvcsAmilnn+oyf2lDHFrTJ0ID3Vw635YWR3PZC5HjMPsGAPTv8sqU1vM7wU9YsS7WiJu+1Czd0EWOCiFmweNwIoE9CnIaehuofMF+fE98fy00MFK5l8b
    admin-user: AgBxDFf8+lzWXp9A2O9o1uCDL90gMDplH8r6mDw3ucC04Vi5R83Ov2iL2z7MU1QhIkXQC5Gpl8THN8iMYupujDC7GWiGDD6RPMFa5TNIovy2paYoNfyH9r3zIhO0gBaqWyQqT+laloJNjxn1nEFBPq7C1ubj42Bp5KVwEj1z2Iz0vBT8sRZI43IjTGSsLWw8Za75Za7eheoV4E5K9dRPPMlg6DuRckvGRhUZVv7nPkd1DpVVKRCu697yE70Kg2DBiqRRSRmkwtzMj77mB48iQ7Ybx650ITW0ud7zK5JhQ0/Bf5WF9F6WbVWNJobwNWT+/Rk75n2vSAVzLQV05SINjlsQ2aqsPQfuRX/pA4vvabfEb1Jh0Jd8+G2roGFNXpuB3zMSzjHKB+kwsSjqYMbFhcDj9GcvfczScnUFkG//by49oKMfGk78w3licBFvpxnz3y2Wf0GAL+qGwpiId7kd6m7HWKlHLEM3VT5RQSBN2T9YNXYXWrj42CqO0t1IdqcE8IeaG2/O+e4QxtsBQf0ojHj9jQaA8YwKqXKebTh9wrU27dBDKhCZQqQQ9depyQUbTGLjgizrrJ30nTQYmgaGhAdiQB7dLRK7oJBEtLbthTTZXMhowoON2DyYCeTWoJahUuaIm+2tt1Pn7l7IfzpwBz4s8tpnRA9WIA65bFUY50yeNiUuF6ruRXxzZS/2dZmi6WAS5ON45Q==
    ldap-toml: AgBkCrihByhjGoncfDGdvkBbFDCbfDdnF68lCnyzmH6Nxl8kB2FeWD5qRIne5koG/J7RpCHnft1RSMoqf76aF+MhV5MvrTodrHWPGLUCjvNNC0ccKNSCnaJ0VG0BhJOwPhJFrfT54QkRkLnucXlMWLYMfui0rMJnaaEX3N+8naWOk+/FSqCTw+k7S3yersgpPeRql3oihlmK+LuRX0SJi4EeLqsVYylpr00GmEGWMkFuJqSPCwGQyWYDToCyG4gDDqeEDsIX6sbuI7HjKtgvyXvx72k5hZUDGE13cWSxewsUEUQ6h6K9r+DfCcHBRiF6U31PMYsPzBeXF94FaMzorAisRzbyE0ueOgBUvU/PVwcNnsynEuUDqOt1ysaNsMSWDH2E3QI7fhJ7IelWTN+YP/5x1t0Q6a4LSi56L2gOMYQr/G+l2nytjMRqftclG0rmYPmBBVFuZCyAihNjgiF2zCyHB7QnzgZUKCBNaHgoUA//6fYUNsXNiolckk/Gy+axVpkJIU7sEXtnmrzPRLNLE21kq2awegIzvz6GCYOns4VAAedngesoECel+qOg8fWso79JBJrkSMihd6HgA9cn7rpsCChp94LSjGE+vMR8TeJnohBioFSHhm9jEyF7IoSl1MI9ZiGmWA6fh+A/f+4S/LuKXAqzIgSiox7oFxzwgiGy2i2YQ24wNdp6qlwacNTr9qU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prod
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 8.3.6
        helm.sh/chart: grafana-6.22.0
      name: prod-grafana
      namespace: kube-prometheus-stack
    type: Opaque

