apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-grafana
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgB7ceap3FSHHHAUdklfj9ySXMdwO+Q0KvqipELiDkkcJFgFU+HZ2TgsvW2zlAu9KjdZyZjb8tJ3xuU+rFfNlDa9SISB3AR8k83AaaNs9ZCTj3CUWt33eJTihA44gCKtUGuTgFhMXkebYl9lwFAXazmLOFOSzBBXhveZCNRIqhOkh4+tw9RrmN/yD16QJGLXG8/sbiIYgdZKFmgbzXHWBEaRahXZeiLVOOpXdFn8SiX2oUBf6wHFxvdX+Etwv9f3jLIuOzlkAU+m/sdACLeaew07hZfmLdnb9g9FtNL5mjjrDTRL/PAxwA2hhldQi5eDeYvVtFaJf9sKotxOE22aNBhsEsixqiIIafdDK8l4xR0XIpYmrH39aM8Pi4pYhsZ5ONm1inqXdxx56NvA4MmmI3/PMB5JibCHjfmjvoec2Gb+ecS/OLpO0/dixkQFUw6swE4lc4K3Rc+QUpuRFcxuOCdsC1JGld9VarKBcxUmKhXd3J/QdmIXQlccoNiRHfQ+lM/wb98DTFcePN1rL55eL2jAjApkpcXjBBAeQvAnDF6dDlqcF1gah2kDhydMNs8LAMxLRcoEXeMk8Pu4kFONHarPXSNC+wU7SFU8DQ0R+c1yRAtUggNwpKm3ykNRlSWhCsDQTd9pay5MJhvn1RmKIcrGDP7lFRafoPMjwgYtV+j9z2XHKPeltJKV1iyKgdw+U8/zTcMfQ9f3Wwj/IY/x3DCi
    admin-user: AgCFvLVQ62hb82O1a8IMMzgEJ3ADnsdjQQw5iUCj0RSjkgU7V9CGawR65x8ecWfK7yzYkstGRmfmB/XyiyFL8butmeZG2TDZTWc9gVQznJaUmghG2sIB56iSwdR6yJl8LWNOEd8MAtmBsg9yo0/n7ZXrzbiHGQxg/v2KREJdr0FR4A7TtuKLL6SBzE84k8YmZenFlhPPpMJiJ+eRjlpFMDApHnTqYCQVDs1kLKt9iIVX64KsmNhsAMpe9dtqITON2uWzP4S3fs4uQSUrMtKM8fZLjsPHUGV/fQcLf6QkT7hmK1pcgrS0Ff+J/tMWPpFouAYhfVm1DE5s9X67xyEw/oCXJ8vbFKwdn1v1a6D36m86uacMOISoIbCv17OFeZAp8ooF/P/BvoRa9ZNV4UWxPr8opvKWYiidLJhMXMJ32E3LxTNyhX9yxAGrENKZ7a52pCYxNRir45gS+XdMuN8rCgdWVTfWqHticXa5gJQ1OFeDJZ8g2AAyWyYqIEoqYPgv7PjukXXA88AlKyMlA9aHvz9hGvu1MP96cd3SXbm3tblNRNm9KUGMRP63+Jn+W7zWiWCNnpoMaco7wMcCOQN81tope/9fG0STk7PJt1evTt1FS9lIVXaj5uDtq+KSj4PHC6gCAKc/POHotEk3/8ADqEpL1EtKtYukGbDJfJZENaZ7Fvt03uuGGaoi+WBJW/7srdrrpPSTPA==
    ldap-toml: AgBoqDqjbj9h1fmL/rmSSobU9M9+k4N+Ux2FCBEVw6HdpW9tWwDOeaivHHc4mBxrTvGYhnJD1B0TIwnzKlLDwEF8OAcYqkBiEBUfeJ8ZE6UBbbLYmbByTP1Ebnkuql82qbwZZ7nY87vNIn4fOQn70H51n3mrgB8KNpbMGXLCN0RCcs5swlaOY7MwBANIWa+R2w40OVuC4EcjqqT2skJN++gWaUiWmvD/d6M9ZR1s4IyflkY29UlzxUqPdcxCZooIZcfBCuJ/lFfujTsnTAdWtxj0iWksjlVkNT+CibAI8xgNCue+84wKtODCaEX8+EtvLgwK/ppK2LsR0T/WbwOWJkhYXvTCX7GfLFz9KU14nDuZZlgd0kwn6e+9sMWK4E91EJMFWAWn1fa87UAgLCJf8lOJJgXsYsyty9e9XLxkoholGP8MHfYXuvBr2+st0BxReAo4Ew/gDlPrSe/PmUoXCsvmWLGQyXcKE4VLPOq1P3tjPORzCZws6HxAqg9zG420y/KUnQlqYgmH+rkSJm6RWnbfKMXNowSFcipMTpz4zAMOtE+5UHhMzoxsTn8VU6snYXTUoAlBl7gRpB+/xvyiZLK6/yi9ookdvePolY8clzMp/+rh/U42bWXByigG6AZ0FVHu93s6rbtkEvlxFDtvw80sowjPC9ocN3PWewWusIyF0szDiX4qfVKP0lOEhj4ar/A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prod
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 8.3.6
        helm.sh/chart: grafana-6.22.0
      name: prod-grafana
      namespace: kube-prometheus-stack
    type: Opaque

