{{- if index .Values "kube-prometheus-stack" "grafana" "enabled" }}
apiVersion: v1
data:
  admin-password: ''
  admin-user: ''
  ldap-toml: ''
kind: Secret
metadata:
  name: prod-kube-prometheus-stack-grafana
  namespace: kube-prometheus-stack
  annotations:
    sealedsecrets.bitnami.com/managed: 'true'
type: Opaque
{{- end }}
