{{- if index .Values "kube-prometheus-stack" "prometheus" "prometheusSpec" "remoteWrite" 0 "basicAuth" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-receive-basic-auth
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    password: AgCZDxnHTaL0r93vezsz6a5Ep/Cpwk9d/7vCSkXi1VYwVL6hj8QT3IyBz99KaYo2NInQcy4rVKNQ+7BsHjQqzDHWJ2JJ9G4wqRjNoycJalNZoFxyRyuUIe8Ivp5nJ091Db321C0+MQC4WibDqRwWtVrzFSutTS7gv+NH/zGDx19w4ukE+DP438pRgxP49DmXeB909Az6dPXdnTCmJ0pcPk4Ud2R5kYIk3CpggzttWQ5wRRH/x9ZM3Csf8xi4+rpFiP2jCs9eGAL8qtyvDUvkd1N8WoSqiwcNitwKQjC4p+uZCkeIAQR88A5RR/7alrjwpe+odkS9vGbMEbMMHxYoq3lumv9ATmB3FHETEINctLT7lqdxUxyngz6r2UF+LNoQakZMMEXPrp6UMY+R7P7q8xdpwzBnDpGErZ6KE2+ls2SMgmeXK5IJ6rK4SDb2vf76UyDAr1PeQbtVUxpk+vbEk1Wm4Xl0Y7rK/CIhcV1PnW1ElaWXCaU9TDSwBZC9/aAUEhRkg8HTB8qlAOkq3090bcYcXX4d2+qOTLkbiAJd2nCjkS5wO1NoJGXBXQ018uNP1e9a6dc8X1ko5ejcpP8JpN3Xr5Y8NsSyTk7gDg+xxvBSsCL+rjQh96yiqrNWBlP11IE0JimD4FVvlyvE/3rhe/JMgwIIx4A1luPyQKVvTUg/srcdRa3K+b6iHXrM9WccqZ6mZmV12SyWTe8J/M54GSi+
    username: AgC5GsI7VpnfjlDwMSLx855qYki0zyjy+A41p2hXDrfaA7007uPyZpl0pa4EGjMTwYont2KahVu7XNkQMZau0L1B5rfxORFYvnZv/Q/oH3MLn5EC5pL6v0auFt9WIaMnB4LxiyA7m75mqtztfIF2oag+NGDWivrm2Tr/QI1yc9+dfhD4/7ibOfTxC157bDkIMfbJk3ShR1jiKlOWCoBQPfUx62MnHfQqKmw+OjHtYyzNwLL8Apae2Wss+LwGnMgNe2WWagmTKmn7oS8C+y+gKYdKdIAdNCG5lfPLy4aw7MOZkZn/0ALK0mOD/g6PtLoAp7WiNoF+f070MpvwrbcjzUUpuUa/rjx0yXxpEWowXAasZXYt1IzyyrLvW2ww7FMe+xLwSqOmMCuYt4wM0Y0b1jrX1goRL58VJ5I6sLtY0CXsZJbSW1Fc/HvzGlQ1e5qH/6iRUfj6dqjsjK8VXrI3sC/stY+AWpeKw/2FYKCUWiDx+QgPvOOdXd49+c+74GLENHsFxBczV66xGxgQbS4X+69Gqw7xtOc0oTkstke8pAVh5NVBqSXOn1sl8XpCKR8gzwBR+Ppbpx6fFyZhkpOeoHh/Wc/ltEb8TYvnqVSotypYwV+/3Qr1MsCFYTsVw1qGYqtcrFPJCiRRt5zSCxfQ9U+hNetTNmRZaNpbGKF4PVSNA4ysCeV+chKVC8jtwteVHg42JhEcOKA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-receive-basic-auth
      namespace: kube-prometheus-stack
    type: Opaque
{{- end }}
