apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-receive-basic-auth
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    password: AgCrk0XMwCJece30hSeJ8B5I8yDJ0qYM4gmMerFwbufdS0EZ71oCSBcZ/b6TrRaUgjSWWMnidBinjgjTGuJTihvJwaUBsABhfCauYFW9GDZYy0K1Ja8TKvhpn+1jtBu77AFe5buTn/2wzGDDqWQ2v6r50nLSaVZZrsLuJ3m2J5X8zJSSikuDPkkWvVKPDwE0VdskmcNOX0Kxsq6cvsTJDZAOQQ6Ng6a/dp31DAXnfJKA30tV76ChINrz2uWl6Jy4C2aIeTiRC6EMnw/FFK/npKhHnMMR1Zu+lzVUXNEgVZ7TfDpwnbFeXTJwfVLeJX6Rn8gaAdAUuWVpgESSOzlaiZMevxyXph+kMD5dhHFG/psLMAaW4MZgLA2zddDvNbXCI6L6iKFrgAHLbNkDBSnGmURZBwzT9vfZpeQbDGdiK6KYB3sX+en5zs148hkrJ1iDDeJAdiCZkxwuIEz0QLmmf/IFdHV5XtcnWV73inqPtPr1CjkvK8XPgSN1ZJDI8Cwjz2ZKLRbqLQ90LoA59HimhpzT9SVY2Bef5fUfRtfqnX9ywStvvtdSg252rnjH9AEdM1PvbrbfGE6SVo7imPKNRuWgQxoSHULRfuzayOhk8k3gNB4Nrs6P4Cw7v2Hd5eztZng3Zm8uDVZoe6mKhthCW1b5YDVjBuoPheYFPDAsxFcPYzlzIfmN1nex1pFq4fhmaUf1QWTnFn2oghHOLYzdrWMj
    username: AgA1OjdkZzigGyZ+ASAkQ5flcyNBqsTWhe2jxDbUqgGxBwrWllB9tDAKSt2Xjtx63fDZUElP+ayFHY9BO1YkvX14vOyRJqoYg75HEqvnmLmmAxewacI4NyG/6jTIFe8FO6MH4gPWP33kwrYCIeNYGTeGJD3iHDhKiuQSrz8qAo72zPWCqlCF/q1Xe0Hx3qEeHQyBXQ9U5YeXCHT3cAd1qEqcMZSa8Ow9kytBUBQ/oQuE5Ad0yw1eWRWrFAPZIXW5MpeLDAfTBNZLn8OTT9063yqVHhkLoq8Fof2qwTEvVMqA0XBAm01ESeyZx87f8vTOmqahwbdZ90GQ1bOCaWqQhjINRH9UWCvKeBYkDW0qRQvprDlcJAOVCyWUVtYdz2VrlMvsEUDy9UiEqNwSPo0IZDHzlo6DnJSAK5qCmX9huc7Fte+6NlaktgljynWCOmh5CdhQArmlCrVC4dCNADQO5PBxriqznzaTep4eXzxwqrPpBnR8K6gKN7vnyvxhrJB0h+9w2L6WiVeEBQfGpdbFnLJ0Pn/PLCtX5jWNzcztwWQ05wMFSIYt6RbL9CF9Ye5dySY6cdVUZzxtqtWo+Nmr6zaCXhxO/pP+xdYMxhDx0Z3+pv4ixIzAXHmn0Uv0wJdWdf2mJMSqvUmOPD6pWHMkZJQePB8ir3L/6QQgDPgdc+f1XFPQfKetj+Z29m17YDr8zuRK/nmcucs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-receive-basic-auth
      namespace: kube-prometheus-stack
    type: Opaque

