apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-receive-basic-auth
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    password: AgBzx6mLddA4QhSNRc9xAx3R3KrdV0gTRhaE9tWVegOYo/USnLYG6HcsYWdhZKGdCKchmJE9fAPb8+c4EOLtsRB9CgEm4hruBM+2iFiy/xNzNtKd7vwcCq+UFIhUQJra0l/KSh9YBCmsj37CahEX8Dsy/A3N0azvrCiA6cw57joDnorT77tmFmtJU/93DD/UIENo+/rhBDQw5dpkRhTx/1xRLmA6FEy6vgsUaSmsnUPzhc+Hd0p1Hjd4TmyOHicOFZMYM/ZMQEUj4obavtkgDoRvL05b4WpOMLiy4oot/Sjiu/EkKbwqTq18HdZUGzEglPR0y4zjYFnrIqpAtvpHypm2sxsERmJdA7Q6QLA28Rt2PuJW0EN4Pg5bdVi5qrmzsdktYDjdANR57k5Xkn/m0T+gem5gI46wRuHDATtKaF50o9Xvzk93tt9FucHHaiIeIKKDJiDywOZHp/781Geazk97GIEIy7RyPYsQuHXkD9OEd1zkhqSXNpJjiZJYpK4om59h9Xw2J8sMPO9PYqTOVMnEea5YLBzJoBAJkuD1NzuyTQ3Acn7Y83P/e62HIr69k4+gcE3d+9AteKc98PScFnpnbYne+8pzYrrG276PAJ2gke5zOAvdvQeOK0dLuV0ub/UYh/RWeAPZfaga5BA7A3AUr8C8zNZH+dAFsgaQT5L2uQG6EbmAV1tt7DHPyAamdZLCcArvVTCOeFXsscvjkvS4
    username: AgBNx3G1wi4N5FXtcI1uoJkMbeJ6CIKYPTHSvIsrO/0RnUI1CTV1+7fNmcK7MhWdfH6oGfryxbPPaxYdfb+TfQuzuqznC0OM8YiFhehN1CEB2DopAzSQeslzoVhd5TmpAqoaWnQxgABsGgHg0jsfyHboSWlDmTeG4bINNwEK5uynT73A6AO1w9kgJQC+L0loCrsOGj+0cY5jMdpoFCAzc5vpJmTOcd9AgRK9GHMuZxm3nDeW+UL+a9qF9rB+9eQqL4pQaH3wFiy9K413iOS1xRrmyghVpAQ0fwWow7zkL+u90usFtnKhj2toqR/6Szkobi02ypjGqTmpdfeJuDYV8AB8z8egQryI1EdCgAm+x/naukw9SsuNBc5evcIVUDjHi1IurVAMXW9BHYWcZ5B2rKFqojgTuDOofsLejgK+KY6di1hYNJn2gYpWilH/sNUMOrqSsVnA31EmPPmiVNE8waRN0UJf1j0rmoZGJQnqdfLH9l0/pjlsuzIlxNkC+nDoH0kZPD7m8hD+dxz2T3yJnic5cmAoHYJW4K1PArbAwAaYBm4BS4jZlOm8odo5fsFMAcDe4BvZDvwKsoGzCx+Ozu9/4NgnF210j+Pq6W1szEymy5K/fSe6mjLFyfdx9V+TUs2bGaZPBRuF4gize8NAP8SyeOxYfSXShSrRw/Rd5R4Q7hWNoYJQqvzuz25TWxDARU3L/LBA/ic=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-receive-basic-auth
      namespace: kube-prometheus-stack
    type: Opaque

