apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: tzkt-indexer
  namespace: mavryk-basenet
spec:
  rules:
  - host: api.mavryk.network
    http:
      paths:
      - backend:
          service:
            name: tzkt-indexer
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.mavryk.network
    secretName: tzkt-indexer-tls
